### ISSUE TITLE
[enhancement] use buffer methods directly, without new wrapper

### ISSUE THREAD

**Issue by grrtrr** [leemcloughlin/expect#2]
_This is an enhancement suggestion, in the interest of a simple and small API._
### Description

The API exposes 2 methods that wrap `bytes.Buffer` calls:

``` go
func (exp *Expect) Clear() {}
func (exp *Expect) BufStr() string {}
```

These calls are _equivalent_ according to
- `e.Clear()` == `e.Buffer.Reset()`
- `e.BufStr()` == `e.Buffer.String()`
### Suggestion

If acceptable, remove, perhaps a test program calling the buffer methods.

**Comment by leemcloughlin** [comment]
Hi

Thanks for the suggestion. I'll consider it but I already have a lot of code using both Clear() and BufStr()

**Comment by grrtrr** [comment]
Thank you - it was something that occurred to me while reading the code.
